# A generic, single database configuration for Alembic.

[alembic]
# path to migration scripts
script_location = database/alembic

# template used to generate migration files
# file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s

# sys.path pathsprepended to front of sys.path.  Defaults to the current directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# timezone =

# max length of characters to apply to the "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow modules to be imported with relative paths
# use_relative_imports = false

# version locations.  specifies where to find version files.
# defaults to database/alembic/versions.
# version_locations = %(here)s/alembic/versions

# version path separator; defaults to os.pathsep.
# Use os.pathsep to list multiple paths in version_locations
# version_path_separator = :

# logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
